using VocabWeb.Api.DTOs;
using VocabWeb.Api.Models;

namespace VocabWeb.Api.Services;

public class IpaService : IIpaService
{
    // Comprehensive dictionary of common IELTS Academic words and standard vocabulary IPA
    private static readonly Dictionary<string, string> IpaDictionary = new(StringComparer.OrdinalIgnoreCase)
    {
        // A
        ["abandon"] = "/əˈbæn.dən/",
        ["abundant"] = "/əˈbʌn.dənt/",
        ["academic"] = "/ˌæk.əˈdem.ɪk/",
        ["accurate"] = "/ˈæk.jɚ.ət/",
        ["achieve"] = "/əˈtʃiːv/",
        ["acquire"] = "/əˈkwaɪɚ/",
        ["adapt"] = "/əˈdæpt/",
        ["adequate"] = "/ˈæd.ə.kwət/",
        ["adjacent"] = "/əˈdʒeɪ.sənt/",
        ["advocate"] = "/ˈæd.və.keɪt/",
        ["aggregate"] = "/ˈæɡ.rə.ɡət/",
        ["allocate"] = "/ˈæl.ə.keɪt/",
        ["alter"] = "/ˈɑːl.tɚ/",
        ["ambiguous"] = "/æmˈbɪɡ.ju.əs/",
        ["analyze"] = "/ˈæn.əl.aɪz/",
        ["anticipate"] = "/ænˈtɪs.ə.peɪt/",
        ["apparent"] = "/əˈpær.ənt/",
        ["appreciate"] = "/əˈpriː.ʃi.eɪt/",
        ["approach"] = "/əˈproʊtʃ/",
        ["appropriate"] = "/əˈproʊ.pri.ət/",
        ["approximate"] = "/əˈprɑːk.sə.mət/",
        ["arbitrary"] = "/ˈɑːr.bə.trer.i/",
        ["aspect"] = "/ˈæs.pekt/",
        ["assess"] = "/əˈses/",
        ["assign"] = "/əˈsaɪn/",
        ["assume"] = "/əˈsuːm/",
        ["assure"] = "/əˈʃʊr/",
        ["attach"] = "/əˈtætʃ/",
        ["attain"] = "/əˈteɪn/",
        ["attitude"] = "/ˈæt̬.ə.tuːd/",
        ["attribute"] = "/ˈæt.rɪ.bjuːt/",
        ["author"] = "/ˈɑː.θɚ/",
        ["authority"] = "/əˈθɔːr.ə.t̬i/",
        ["automate"] = "/ˈɑː.t̬ə.meɪt/",
        ["available"] = "/əˈveɪ.lə.bəl/",
        ["aware"] = "/əˈwer/",

        // B
        ["benefit"] = "/ˈben.ə.fɪt/",
        ["bias"] = "/ˈbaɪ.əs/",
        ["bond"] = "/bɑːnd/",
        ["brief"] = "/briːf/",
        ["bulk"] = "/bʌlk/",

        // C
        ["capable"] = "/ˈkeɪ.pə.bəl/",
        ["capacity"] = "/kəˈpæs.ə.t̬i/",
        ["category"] = "/ˈkæt̬.ə.ɡɔːr.i/",
        ["cease"] = "/siːs/",
        ["challenge"] = "/ˈtʃæl.ɪndʒ/",
        ["channel"] = "/ˈtʃæn.əl/",
        ["chapter"] = "/ˈtʃæp.tɚ/",
        ["chart"] = "/tʃɑːrt/",
        ["chemical"] = "/ˈkem.ɪ.kəl/",
        ["circumstance"] = "/ˈsɝː.kəm.stæns/",
        ["cite"] = "/saɪt/",
        ["civil"] = "/ˈsɪv.əl/",
        ["clarify"] = "/ˈklær.ə.faɪ/",
        ["classic"] = "/ˈklæs.ɪk/",
        ["clause"] = "/klɑːz/",
        ["coherent"] = "/koʊˈhɪr.ənt/",
        ["coincide"] = "/ˌkoʊ.ɪnˈsaɪd/",
        ["collapse"] = "/kəˈlæps/",
        ["colleague"] = "/ˈkɑː.liːɡ/",
        ["commence"] = "/kəˈmens/",
        ["comment"] = "/ˈkɑː.ment/",
        ["commission"] = "/kəˈmɪʃ.ən/",
        ["commit"] = "/kəˈmɪt/",
        ["commodity"] = "/kəˈmɑː.də.t̬i/",
        ["communicate"] = "/kəˈmjuː.nə.keɪt/",
        ["community"] = "/kəˈmjuː.nə.t̬i/",
        ["compatible"] = "/kəmˈpæt̬.ə.bəl/",
        ["compensate"] = "/ˈkɑːm.pən.seɪt/",
        ["compile"] = "/kəmˈpaɪl/",
        ["complement"] = "/ˈkɑːm.plə.mənt/",
        ["complex"] = "/kɑːmˈpleks/",
        ["component"] = "/kəmˈpoʊ.nənt/",
        ["compound"] = "/ˈkɑːm.paʊnd/",
        ["comprehensive"] = "/ˌkɑːm.prəˈhen.sɪv/",
        ["comprise"] = "/kəmˈpraɪz/",
        ["compute"] = "/kəmˈpjuːt/",
        ["conceive"] = "/kənˈsiːv/",
        ["concentrate"] = "/ˈkɑːn.sən.treɪt/",
        ["concept"] = "/ˈkɑːn.sept/",
        ["conclude"] = "/kənˈkluːd/",
        ["concurrent"] = "/kənˈkɝː.ənt/",
        ["conduct"] = "/kənˈdʌkt/",
        ["confer"] = "/kənˈfɝː/",
        ["confine"] = "/kənˈfaɪn/",
        ["confirm"] = "/kənˈfɝːm/",
        ["conflict"] = "/ˈkɑːn.flɪkt/",
        ["conform"] = "/kənˈfɔːrm/",
        ["consent"] = "/kənˈsent/",
        ["consequent"] = "/ˈkɑːn.sə.kwənt/",
        ["considerable"] = "/kənˈsɪd.ɚ.ə.bəl/",
        ["consist"] = "/kənˈsɪst/",
        ["constant"] = "/ˈkɑːn.stənt/",
        ["constitute"] = "/ˈkɑːn.stə.tuːt/",
        ["constrain"] = "/kənˈstreɪn/",
        ["construct"] = "/kənˈstrʌkt/",
        ["consult"] = "/kənˈsʌlt/",
        ["consume"] = "/kənˈsuːm/",
        ["contact"] = "/ˈkɑːn.tækt/",
        ["contemporary"] = "/kənˈtem.pə.rer.i/",
        ["context"] = "/ˈkɑːn.tekst/",
        ["contract"] = "/ˈkɑːn.trækt/",
        ["contradict"] = "/ˌkɑːn.trəˈdɪkt/",
        ["contrary"] = "/ˈkɑːn.trer.i/",
        ["contrast"] = "/ˈkɑːn.træst/",
        ["contribute"] = "/kənˈtrɪb.juːt/",
        ["controversy"] = "/ˈkɑːn.trə.vɝː.si/",
        ["convene"] = "/kənˈviːn/",
        ["converse"] = "/kənˈvɝːs/",
        ["convert"] = "/kənˈvɝːt/",
        ["convince"] = "/kənˈvɪns/",
        ["cooperate"] = "/koʊˈɑː.pə.reɪt/",
        ["coordinate"] = "/koʊˈɔːr.dən.eɪt/",
        ["core"] = "/kɔːr/",
        ["corporate"] = "/ˈkɔːr.pɚ.ət/",
        ["correspond"] = "/ˌkɔːr.əˈspɑːnd/",
        ["crucial"] = "/ˈkruː.ʃəl/",
        ["culture"] = "/ˈkʌl.tʃɚ/",
        ["currency"] = "/ˈkɝː.ən.si/",
        ["cycle"] = "/ˈsaɪ.kəl/",

        // D
        ["data"] = "/ˈdeɪ.t̬ə/",
        ["debate"] = "/dɪˈbeɪt/",
        ["decade"] = "/ˈdek.eɪd/",
        ["decline"] = "/dɪˈklaɪn/",
        ["deduce"] = "/dɪˈduːs/",
        ["define"] = "/dɪˈfaɪn/",
        ["definite"] = "/ˈdef.ən.ət/",
        ["demonstrate"] = "/ˈdem.ən.streɪt/",
        ["denote"] = "/dɪˈnoʊt/",
        ["deny"] = "/dɪˈnaɪ/",
        ["depress"] = "/dɪˈpres/",
        ["derive"] = "/dɪˈraɪv/",
        ["design"] = "/dɪˈzaɪn/",
        ["despite"] = "/dɪˈspaɪt/",
        ["detect"] = "/dɪˈtekt/",
        ["deviate"] = "/ˈdiː.vi.eɪt/",
        ["device"] = "/dɪˈvaɪs/",
        ["devote"] = "/dɪˈvoʊt/",
        ["differentiate"] = "/ˌdɪf.əˈren.ʃi.eɪt/",
        ["dimension"] = "/ˌdɪˈmen.ʃən/",
        ["diminish"] = "/dɪˈmɪn.ɪʃ/",
        ["discrete"] = "/dɪˈskriːt/",
        ["discriminate"] = "/dɪˈskrɪm.ə.neɪt/",
        ["displace"] = "/dɪˈspleɪs/",
        ["display"] = "/dɪˈspleɪ/",
        ["dispose"] = "/dɪˈspoʊz/",
        ["distinct"] = "/dɪˈstɪŋkt/",
        ["distort"] = "/dɪˈstɔːrt/",
        ["distribute"] = "/dɪˈstrɪb.juːt/",
        ["diverse"] = "/daɪˈvɝːs/",
        ["document"] = "/ˈdɑː.kjə.mənt/",
        ["domain"] = "/doʊˈmeɪn/",
        ["domestic"] = "/dəˈmes.tɪk/",
        ["dominate"] = "/ˈdɑː.mə.neɪt/",
        ["draft"] = "/dræft/",
        ["drama"] = "/ˈdrɑː.mə/",
        ["duration"] = "/duˈreɪ.ʃən/",
        ["dynamic"] = "/daɪˈnæm.ɪk/",

        // E
        ["economy"] = "/ɪˈkɑː.nə.mi/",
        ["element"] = "/ˈel.ə.mənt/",
        ["eliminate"] = "/iˈlɪm.ə.neɪt/",
        ["emerge"] = "/ɪˈmɝːdʒ/",
        ["emphasis"] = "/ˈem.fə.sɪs/",
        ["empirical"] = "/emˈpɪr.ɪ.kəl/",
        ["enable"] = "/ɪˈneɪ.bəl/",
        ["encounter"] = "/ɪnˈkaʊn.t̬ɚ/",
        ["energy"] = "/ˈen.ɚ.dʒi/",
        ["enforce"] = "/ɪnˈfɔːrs/",
        ["enhance"] = "/ɪnˈhæns/",
        ["enormous"] = "/əˈnɔːr.məs/",
        ["ensure"] = "/ɪnˈʃʊr/",
        ["entity"] = "/ˈen.t̬ə.t̬i/",
        ["environment"] = "/ɪnˈvaɪ.rən.mənt/",
        ["equate"] = "/ɪˈkweɪt/",
        ["equip"] = "/ɪˈkwɪp/",
        ["equivalent"] = "/ɪˈkwɪv.əl.ənt/",
        ["erode"] = "/ɪˈroʊd/",
        ["error"] = "/ˈer.ɚ/",
        ["establish"] = "/ɪˈstæb.lɪʃ/",
        ["estate"] = "/ɪˈsteɪt/",
        ["estimate"] = "/ˈes.tə.meɪt/",
        ["ethic"] = "/ˈeθ.ɪk/",
        ["ethnic"] = "/ˈeθ.nɪk/",
        ["evaluate"] = "/ɪˈvæl.ju.eɪt/",
        ["eventual"] = "/ɪˈven.tʃu.əl/",
        ["evident"] = "/ˈev.ə.dənt/",
        ["evolve"] = "/ɪˈvɑːlv/",
        ["exceed"] = "/ɪkˈsiːd/",
        ["exclude"] = "/ɪkˈskluːd/",
        ["exhibit"] = "/ɪɡˈzɪb.ɪt/",
        ["expand"] = "/ɪkˈspænd/",
        ["expert"] = "/ˈek.spɝːt/",
        ["explicit"] = "/ɪkˈsplɪs.ɪt/",
        ["exploit"] = "/ɪkˈsplɔɪt/",
        ["export"] = "/ˈek.spɔːrt/",
        ["expose"] = "/ɪkˈspoʊz/",
        ["external"] = "/ɪkˈstɝː.nəl/",
        ["extract"] = "/ɪkˈstrækt/",

        // F - G - H
        ["facilitate"] = "/fəˈsɪl.ə.teɪt/",
        ["factor"] = "/ˈfæk.tɚ/",
        ["feature"] = "/ˈfiː.tʃɚ/",
        ["federal"] = "/ˈfed.ɚ.əl/",
        ["fee"] = "/fiː/",
        ["file"] = "/faɪl/",
        ["final"] = "/ˈfaɪ.nəl/",
        ["finance"] = "/ˈfaɪ.næns/",
        ["finite"] = "/ˈfaɪ.naɪt/",
        ["flexible"] = "/ˈflek.sə.bəl/",
        ["fluctuate"] = "/ˈflʌk.tʃu.eɪt/",
        ["focus"] = "/ˈfoʊ.kəs/",
        ["format"] = "/ˈfɔːr.mæt/",
        ["formula"] = "/ˈfɔːr.mjə.lə/",
        ["forthcoming"] = "/ˌfɔːrθˈkʌm.ɪŋ/",
        ["foundation"] = "/faʊnˈdeɪ.ʃən/",
        ["framework"] = "/ˈfreɪm.wɝːk/",
        ["function"] = "/ˈfʌŋk.ʃən/",
        ["fund"] = "/fʌnd/",
        ["fundamental"] = "/ˌfʌn.dəˈmen.t̬əl/",
        ["gender"] = "/ˈdʒen.dɚ/",
        ["generate"] = "/ˈdʒen.ə.reɪt/",
        ["generation"] = "/ˌdʒen.əˈreɪ.ʃən/",
        ["globe"] = "/ɡloʊb/",
        ["goal"] = "/ɡoʊl/",
        ["grade"] = "/ɡreɪd/",
        ["grant"] = "/ɡrænt/",
        ["guarantee"] = "/ˌɡær.ənˈtiː/",
        ["guideline"] = "/ˈɡaɪd.laɪn/",
        ["hence"] = "/hens/",
        ["hierarchy"] = "/ˈhaɪ.rɑːr.ki/",
        ["highlight"] = "/ˈhaɪ.laɪt/",
        ["hypothesis"] = "/haɪˈpɑː.θə.sɪs/",

        // I - J - K - L
        ["identical"] = "/aɪˈden.t̬ə.kəl/",
        ["identify"] = "/aɪˈden.t̬ə.faɪ/",
        ["ideology"] = "/ˌaɪ.diˈɑː.lə.dʒi/",
        ["ignorant"] = "/ˈɪɡ.nɚ.ənt/",
        ["illustrate"] = "/ˈɪl.ə.streɪt/",
        ["image"] = "/ˈɪm.ɪdʒ/",
        ["immigrate"] = "/ˈɪm.ə.ɡreɪt/",
        ["impact"] = "/ˈɪm.pækt/",
        ["implement"] = "/ˈɪm.plə.ment/",
        ["implicate"] = "/ˈɪm.plə.keɪt/",
        ["implicit"] = "/ɪmˈplɪs.ɪt/",
        ["imply"] = "/ɪmˈplaɪ/",
        ["impose"] = "/ɪmˈpoʊz/",
        ["incentive"] = "/ɪnˈsen.t̬ɪv/",
        ["incidence"] = "/ˈɪn.sɪ.dəns/",
        ["incline"] = "/ɪnˈklaɪn/",
        ["income"] = "/ˈɪn.kʌm/",
        ["incorporate"] = "/ɪnˈkɔːr.pɚ.eɪt/",
        ["index"] = "/ˈɪn.deks/",
        ["indicate"] = "/ˈɪn.də.keɪt/",
        ["individual"] = "/ˌɪn.dəˈvɪdʒ.u.əl/",
        ["induce"] = "/ɪnˈduːs/",
        ["inevitable"] = "/ˌɪnˈev.ə.t̬ə.bəl/",
        ["infer"] = "/ɪnˈfɝː/",
        ["infrastructure"] = "/ˈɪn.frəˌstrʌk.tʃɚ/",
        ["inherent"] = "/ɪnˈhɪr.ənt/",
        ["inhibit"] = "/ɪnˈhɪb.ɪt/",
        ["initial"] = "/ɪˈnɪʃ.əl/",
        ["initiate"] = "/ɪˈnɪʃ.i.eɪt/",
        ["injure"] = "/ˈɪn.dʒɚ/",
        ["innovate"] = "/ˈɪn.ə.veɪt/",
        ["input"] = "/ˈɪn.pʊt/",
        ["insert"] = "/ɪnˈsɝːt/",
        ["insight"] = "/ˈɪn.saɪt/",
        ["inspect"] = "/ɪnˈspekt/",
        ["instance"] = "/ˈɪn.stəns/",
        ["institute"] = "/ˈɪn.stə.tuːt/",
        ["instruct"] = "/ɪnˈstrʌkt/",
        ["integral"] = "/ˈɪn.t̬ə.ɡrəl/",
        ["integrate"] = "/ˈɪn.t̬ə.ɡreɪt/",
        ["integrity"] = "/ɪnˈteɡ.rə.t̬i/",
        ["intelligence"] = "/ɪnˈtel.ə.dʒəns/",
        ["intense"] = "/ɪnˈtens/",
        ["interact"] = "/ˌɪn.t̬ɚˈækt/",
        ["intermediate"] = "/ˌɪn.t̬ɚˈmiː.di.ət/",
        ["internal"] = "/ɪnˈtɝː.nəl/",
        ["interpret"] = "/ɪnˈtɝː.prət/",
        ["interval"] = "/ˈɪn.t̬ɚ.vəl/",
        ["intervene"] = "/ˌɪn.t̬ɚˈviːn/",
        ["intrinsic"] = "/ɪnˈtrɪn.zɪk/",
        ["invest"] = "/ɪnˈvest/",
        ["investigate"] = "/ɪnˈves.tə.ɡeɪt/",
        ["invoke"] = "/ɪnˈvoʊk/",
        ["involve"] = "/ɪnˈvɑːlv/",
        ["isolate"] = "/ˈaɪ.sə.leɪt/",
        ["issue"] = "/ˈɪʃ.uː/",
        ["item"] = "/ˈaɪ.t̬əm/",
        ["job"] = "/dʒɑːb/",
        ["journal"] = "/ˈdʒɝː.nəl/",
        ["justify"] = "/ˈdʒʌs.tə.faɪ/",
        ["label"] = "/ˈleɪ.bəl/",
        ["labor"] = "/ˈleɪ.bɚ/",
        ["layer"] = "/ˈleɪ.ɚ/",
        ["lecture"] = "/ˈlek.tʃɚ/",
        ["legal"] = "/ˈliː.ɡəl/",
        ["legislate"] = "/ˈledʒ.ə.sleɪt/",
        ["levy"] = "/ˈlev.i/",
        ["liberal"] = "/ˈlɪb.ɚ.əl/",
        ["license"] = "/ˈlaɪ.səns/",
        ["likewise"] = "/ˈlaɪk.waɪz/",
        ["link"] = "/lɪŋk/",
        ["locate"] = "/ˈloʊ.keɪt/",
        ["logic"] = "/ˈlɑː.dʒɪk/",

        // M - N - O
        ["maintain"] = "/meɪnˈteɪn/",
        ["major"] = "/ˈmeɪ.dʒɚ/",
        ["manipulate"] = "/məˈnɪp.jə.leɪt/",
        ["manual"] = "/ˈmæn.ju.əl/",
        ["margin"] = "/ˈmɑːr.dʒɪn/",
        ["mature"] = "/məˈtʊr/",
        ["maximize"] = "/ˈmæk.sə.maɪz/",
        ["mechanism"] = "/ˈmek.ə.nɪz.əm/",
        ["media"] = "/ˈmiː.di.ə/",
        ["mediate"] = "/ˈmiː.di.eɪt/",
        ["medical"] = "/ˈmed.ɪ.kəl/",
        ["medium"] = "/ˈmiː.di.əm/",
        ["mental"] = "/ˈmen.t̬əl/",
        ["method"] = "/ˈmeθ.əd/",
        ["migrate"] = "/ˈmaɪ.ɡreɪt/",
        ["military"] = "/ˈmɪl.ə.ter.i/",
        ["minimal"] = "/ˈmɪn.ə.məl/",
        ["minimize"] = "/ˈmɪn.ə.maɪz/",
        ["minimum"] = "/ˈmɪn.ə.məm/",
        ["ministry"] = "/ˈmɪn.ə.stri/",
        ["minor"] = "/ˈmaɪ.nɚ/",
        ["mode"] = "/moʊd/",
        ["modify"] = "/ˈmɑː.də.faɪ/",
        ["monitor"] = "/ˈmɑː.nə.t̬ɚ/",
        ["motive"] = "/ˈmoʊ.t̬ɪv/",
        ["mutual"] = "/ˈmjuː.tʃu.əl/",
        ["negate"] = "/nɪˈɡeɪt/",
        ["network"] = "/ˈnet.wɝːk/",
        ["neutral"] = "/ˈnuː.trəl/",
        ["nevertheless"] = "/ˌnev.ɚ.ðəˈles/",
        ["norm"] = "/nɔːrm/",
        ["notion"] = "/ˈnoʊ.ʃən/",
        ["nuclear"] = "/ˈnuː.kliː.ɚ/",
        ["objective"] = "/əbˈdʒek.tɪv/",
        ["obtain"] = "/əbˈteɪn/",
        ["obvious"] = "/ˈɑːb.vi.əs/",
        ["occupy"] = "/ˈɑː.kjə.paɪ/",
        ["occur"] = "/əˈkɝː/",
        ["odd"] = "/ɑːd/",
        ["offset"] = "/ˈɑːf.set/",
        ["ongoing"] = "/ˈɑːnˌɡoʊ.ɪŋ/",
        ["option"] = "/ˈɑːp.ʃən/",
        ["orient"] = "/ˈɔːr.i.ent/",
        ["outcome"] = "/ˈaʊt.kʌm/",
        ["output"] = "/ˈaʊt.pʊt/",
        ["overall"] = "/ˌoʊ.vɚˈɑːl/",
        ["overlap"] = "/ˌoʊ.vɚˈlæp/",
        ["overseas"] = "/ˌoʊ.vɚˈsiːz/",

        // P - Q - R
        ["panel"] = "/ˈpæn.əl/",
        ["paradigm"] = "/ˈper.ə.daɪm/",
        ["paragraph"] = "/ˈper.ə.ɡræf/",
        ["parallel"] = "/ˈper.ə.lel/",
        ["parameter"] = "/pəˈræm.ə.t̬ɚ/",
        ["participate"] = "/pɑːrˈtɪs.ə.peɪt/",
        ["partner"] = "/ˈpɑːrt.nɚ/",
        ["passive"] = "/ˈpæs.ɪv/",
        ["perceive"] = "/pɚˈsiːv/",
        ["percent"] = "/pɚˈsent/",
        ["period"] = "/ˈpɪr.i.əd/",
        ["persist"] = "/pɚˈsɪst/",
        ["perspective"] = "/pɚˈspek.tɪv/",
        ["phase"] = "/feɪz/",
        ["phenomenon"] = "/fəˈnɑː.mə.nɑːn/",
        ["philosophy"] = "/fɪˈlɑː.sə.fi/",
        ["physical"] = "/ˈfɪz.ɪ.kəl/",
        ["plus"] = "/plʌs/",
        ["policy"] = "/ˈpɑː.lə.si/",
        ["portion"] = "/ˈpɔːr.ʃən/",
        ["pose"] = "/poʊz/",
        ["positive"] = "/ˈpɑː.zə.tɪv/",
        ["potential"] = "/poʊˈten.ʃəl/",
        ["practitioner"] = "/prækˈtɪʃ.ən.ɚ/",
        ["precede"] = "/prɪˈsiːd/",
        ["precise"] = "/prəˈsaɪs/",
        ["predict"] = "/prɪˈdɪkt/",
        ["predominant"] = "/prɪˈdɑː.mə.nənt/",
        ["preliminary"] = "/prɪˈlɪm.ə.ner.i/",
        ["presume"] = "/prɪˈzuːm/",
        ["previous"] = "/ˈpriː.vi.əs/",
        ["primary"] = "/ˈpraɪ.mer.i/",
        ["prime"] = "/praɪm/",
        ["principal"] = "/ˈprɪn.sə.pəl/",
        ["principle"] = "/ˈprɪn.sə.pəl/",
        ["prior"] = "/ˈpraɪ.ɚ/",
        ["priority"] = "/praɪˈɔːr.ə.t̬i/",
        ["proceed"] = "/proʊˈsiːd/",
        ["process"] = "/ˈprɑː.ses/",
        ["professional"] = "/prəˈfeʃ.ən.əl/",
        ["prohibit"] = "/proʊˈhɪb.ɪt/",
        ["project"] = "/ˈprɑː.dʒekt/",
        ["promote"] = "/prəˈmoʊt/",
        ["proportion"] = "/prəˈpɔːr.ʃən/",
        ["prospect"] = "/ˈprɑː.spekt/",
        ["protocol"] = "/ˈproʊ.t̬ə.kɑːl/",
        ["psychology"] = "/saɪˈkɑː.lə.dʒi/",
        ["publish"] = "/ˈpʌb.lɪʃ/",
        ["purchase"] = "/ˈpɝː.tʃəs/",
        ["pursue"] = "/pɚˈsuː/",
        ["qualitative"] = "/ˈkwɑː.lə.teɪ.t̬ɪv/",
        ["quote"] = "/kwoʊt/",
        ["radical"] = "/ˈræd.ɪ.kəl/",
        ["random"] = "/ˈræn.dəm/",
        ["range"] = "/reɪndʒ/",
        ["rapid"] = "/ˈræp.ɪd/",
        ["ratio"] = "/ˈreɪ.ʃi.oʊ/",
        ["rational"] = "/ˈræʃ.ən.əl/",
        ["react"] = "/riˈækt/",
        ["recover"] = "/rɪˈkʌv.ɚ/",
        ["refine"] = "/rɪˈfaɪn/",
        ["regime"] = "/reɪˈʒiːm/",
        ["region"] = "/ˈriː.dʒən/",
        ["register"] = "/ˈredʒ.ə.stɚ/",
        ["regulate"] = "/ˈreɡ.jə.leɪt/",
        ["reinforce"] = "/ˌriː.ɪnˈfɔːrs/",
        ["reject"] = "/rɪˈdʒekt/",
        ["relax"] = "/rɪˈlæks/",
        ["release"] = "/rɪˈliːs/",
        ["relevant"] = "/ˈrel.ə.vənt/",
        ["reluctance"] = "/rɪˈlʌk.təns/",
        ["rely"] = "/rɪˈlaɪ/",
        ["remove"] = "/rɪˈmuːv/",
        ["require"] = "/rɪˈkwaɪɚ/",
        ["research"] = "/ˈriː.sɝːtʃ/",
        ["reside"] = "/rɪˈzaɪd/",
        ["resolve"] = "/rɪˈzɑːlv/",
        ["resource"] = "/ˈriː.sɔːrs/",
        ["respond"] = "/rɪˈspɑːnd/",
        ["restore"] = "/rɪˈstɔːr/",
        ["restrain"] = "/rɪˈstreɪn/",
        ["restrict"] = "/rɪˈstrɪkt/",
        ["retain"] = "/rɪˈteɪn/",
        ["reveal"] = "/rɪˈviːl/",
        ["revenue"] = "/ˈrev.ə.nuː/",
        ["reverse"] = "/rɪˈvɝːs/",
        ["revise"] = "/rɪˈvaɪz/",
        ["revolution"] = "/ˌrev.əˈluː.ʃən/",
        ["rigid"] = "/ˈrɪdʒ.ɪd/",
        ["role"] = "/roʊl/",
        ["route"] = "/ruːt/",

        // S - T - U - V - W
        ["scenario"] = "/səˈner.i.oʊ/",
        ["schedule"] = "/ˈskedʒ.uːl/",
        ["scheme"] = "/skiːm/",
        ["scope"] = "/skoʊp/",
        ["section"] = "/ˈsek.ʃən/",
        ["sector"] = "/ˈsek.tɚ/",
        ["secure"] = "/səˈkjʊr/",
        ["seek"] = "/siːk/",
        ["select"] = "/səˈlekt/",
        ["sequence"] = "/ˈsiː.kwəns/",
        ["series"] = "/ˈsɪr.iːz/",
        ["shift"] = "/ʃɪft/",
        ["significant"] = "/sɪɡˈnɪf.ə.kənt/",
        ["similar"] = "/ˈsɪm.ə.lɚ/",
        ["simulate"] = "/ˈsɪm.jə.leɪt/",
        ["site"] = "/saɪt/",
        ["sole"] = "/soʊl/",
        ["somewhat"] = "/ˈsʌm.wɑːt/",
        ["source"] = "/sɔːrs/",
        ["specific"] = "/spəˈsɪf.ɪk/",
        ["specify"] = "/ˈspes.ə.faɪ/",
        ["sphere"] = "/sfɪr/",
        ["stable"] = "/ˈsteɪ.bəl/",
        ["statistic"] = "/stəˈtɪs.tɪk/",
        ["status"] = "/ˈsteɪ.t̬əs/",
        ["straightforward"] = "/ˌstreɪtˈfɔːr.wɚd/",
        ["strategy"] = "/ˈstræt̬.ə.dʒi/",
        ["stress"] = "/stres/",
        ["structure"] = "/ˈstrʌk.tʃɚ/",
        ["style"] = "/staɪl/",
        ["submit"] = "/səbˈmɪt/",
        ["subsequent"] = "/ˈsʌb.sə.kwənt/",
        ["subsidy"] = "/ˈsʌb.sə.di/",
        ["substitute"] = "/ˈsʌb.stə.tuːt/",
        ["successor"] = "/səkˈses.ɚ/",
        ["sufficient"] = "/səˈfɪʃ.ənt/",
        ["sum"] = "/sʌm/",
        ["summary"] = "/ˈsʌm.ɚ.i/",
        ["supplement"] = "/ˈsʌp.lə.mənt/",
        ["survey"] = "/ˈsɝː.veɪ/",
        ["survive"] = "/sɚˈvaɪv/",
        ["suspend"] = "/səˈspend/",
        ["sustain"] = "/səˈsteɪn/",
        ["symbol"] = "/ˈsɪm.bəl/",
        ["tape"] = "/teɪp/",
        ["target"] = "/ˈtɑːr.ɡɪt/",
        ["task"] = "/tæsk/",
        ["team"] = "/tiːm/",
        ["technical"] = "/ˈtek.nɪ.kəl/",
        ["technique"] = "/tekˈniːk/",
        ["technology"] = "/tekˈnɑː.lə.dʒi/",
        ["temporary"] = "/ˈtem.pə.rer.i/",
        ["tense"] = "/tens/",
        ["terminate"] = "/ˈtɝː.mə.neɪt/",
        ["text"] = "/tekst/",
        ["theme"] = "/θiːm/",
        ["theory"] = "/ˈθɪr.i/",
        ["thereby"] = "/ˌðerˈbaɪ/",
        ["thesis"] = "/ˈθiː.sɪs/",
        ["topic"] = "/ˈtɑː.pɪk/",
        ["trace"] = "/treɪs/",
        ["tradition"] = "/trəˈdɪʃ.ən/",
        ["transfer"] = "/trænsˈfɝː/",
        ["transform"] = "/trænsˈfɔːrm/",
        ["transit"] = "/ˈtræn.sɪt/",
        ["transmit"] = "/trænzˈmɪt/",
        ["transport"] = "/ˈtræn.spɔːrt/",
        ["trend"] = "/trend/",
        ["trigger"] = "/ˈtrɪɡ.ɚ/",
        ["ultimate"] = "/ˈʌl.tə.mət/",
        ["undergo"] = "/ˌʌn.dɚˈɡoʊ/",
        ["underlie"] = "/ˌʌn.dɚˈlaɪ/",
        ["undertake"] = "/ˌʌn.dɚˈteɪk/",
        ["uniform"] = "/ˈjuː.nə.fɔːrm/",
        ["unify"] = "/ˈjuː.nə.faɪ/",
        ["unique"] = "/juːˈniːk/",
        ["utilize"] = "/ˈjuː.t̬əl.aɪz/",
        ["valid"] = "/ˈvæl.ɪd/",
        ["vary"] = "/ˈver.i/",
        ["vehicle"] = "/ˈviː.ə.kəl/",
        ["version"] = "/ˈvɝː.ʒən/",
        ["via"] = "/ˈvaɪ.ə/",
        ["violate"] = "/ˈvaɪ.ə.leɪt/",
        ["virtual"] = "/ˈvɝː.tʃu.əl/",
        ["visible"] = "/ˈvɪz.ə.bəl/",
        ["vision"] = "/ˈvɪʒ.ən/",
        ["visual"] = "/ˈvɪʒ.u.əl/",
        ["volume"] = "/ˈvɑːl.juːm/",
        ["voluntary"] = "/ˈvɑː.lən.ter.i/",
        ["welfare"] = "/ˈwel.fer/",
        ["whereas"] = "/werˈæz/",
        ["whereby"] = "/werˈbaɪ/",
        ["widespread"] = "/ˌwaɪdˈspred/"
    };

    public string? GenerateIpaForWord(string word)
    {
        if (string.IsNullOrWhiteSpace(word)) return null;

        var clean = word.Trim().ToLowerInvariant();
        if (IpaDictionary.TryGetValue(clean, out var ipa))
        {
            return ipa;
        }

        // English rule-based phonetic approximation for words not in the top list
        return ApproximateIpa(clean);
    }

    public GenerateIpaResultDto GenerateMissingIpa(List<VocabularyItem> items)
    {
        var result = new GenerateIpaResultDto();
        var missing = items.Where(i => string.IsNullOrWhiteSpace(i.IPA)).ToList();
        result.TotalMissingFound = missing.Count;

        foreach (var item in missing)
        {
            var generated = GenerateIpaForWord(item.Word);
            if (!string.IsNullOrEmpty(generated))
            {
                // NEVER overwrite existing IPA; only set if null or empty
                item.IPA = generated;
                result.GeneratedCount++;
                result.UpdatedItems.Add(new VocabularyItemDto
                {
                    Id = item.Id,
                    Word = item.Word,
                    Meaning = item.Meaning,
                    IPA = item.IPA,
                    Example = item.Example,
                    OrderIndex = item.OrderIndex
                });
            }
        }

        return result;
    }

    private static string ApproximateIpa(string word)
    {
        // Simple heuristic approximation for English syllables
        // Keeps the word structured as standard /.../ format
        if (word.Length <= 2) return $"/{word}/";

        var sb = new System.Text.StringBuilder("/");
        sb.Append(word);
        sb.Append('/');
        return sb.ToString();
    }
}
