namespace VocabWeb.Api.DTOs.Learn;

public class StudentQuestionOptionDto
{
    public int VocabularyItemId { get; set; }
    public string Text { get; set; } = string.Empty;
}

public class StudentQuestionDto
{
    public string Id { get; set; } = string.Empty; // Local question ID generated by engine
    public int QuestionIndex { get; set; }
    public string Prompt { get; set; } = string.Empty;
    public string? TargetWord { get; set; }
    public string? TargetMeaning { get; set; }
    
    // Do NOT include CorrectAnswer here!
    public List<StudentQuestionOptionDto>? Options { get; set; }
    
    // Used for pronunciation / listening
    public string? AudioBehavior { get; set; }
}

public class CurrentStageDto
{
    public int StageIndex { get; set; }
    public int TotalStages { get; set; }
    public string ActivityType { get; set; } = string.Empty;
    public string ActivityTypeLabel { get; set; } = string.Empty;
    public List<StudentQuestionDto> Questions { get; set; } = new();
}

public class SubmitStageRequestDto
{
    public List<StudentAnswerSubmissionDto> Answers { get; set; } = new();
}

public class StudentAnswerSubmissionDto
{
    public string QuestionId { get; set; } = string.Empty;
    public int TargetVocabularyItemId { get; set; }
    public string AnswerValue { get; set; } = string.Empty;
    public bool TechnicalFailure { get; set; }
}

public class ActivityResultDto
{
    public string ActivityType { get; set; } = string.Empty;
    public string ActivityTypeLabel { get; set; } = string.Empty;
    public int CorrectCount { get; set; }
    public int IncorrectCount { get; set; }
    public int InvalidCount { get; set; }
    public int TotalValidQuestions { get; set; }
    public decimal Accuracy { get; set; }
    public bool IsLastActivity { get; set; }
}
